export const UserActionTypes = {
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  GOOGLE_SIGN_IN_START: 'SET_GOOGLE_SIGN_IN_START',
  GOOGLE_SIGN_IN_SUCCESS: 'SET_GOOGLE_SIGN_IN_SUCCESS',
  GOOGLE_SIGN_IN_FAILURE: 'SET_GOOGLE_SIGN_IN_FAILURE'
};
